all:
	g++ -std=c++11 pose.cpp -o pose -L/opt/ros/kinetic/lib -I/opt/ros/kinetic/include/opencv-3.1.0-dev -I/usr/local/include -L/usr/local/include -L/opt/vc/lib -lopencv_calib3d3 -lopencv_imgcodecs3 -lraspicam -lraspicam_cv -lopencv_core3 -lopencv_highgui3 -lmmal -lmmal_core -lmmal_util
