// Generated by gencpp from file om17/CellCost.msg
// DO NOT EDIT!


#ifndef OM17_MESSAGE_CELLCOST_H
#define OM17_MESSAGE_CELLCOST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace om17
{
template <class ContainerAllocator>
struct CellCost_
{
  typedef CellCost_<ContainerAllocator> Type;

  CellCost_()
    : x(0)
    , y(0)
    , cost(0.0)  {
    }
  CellCost_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , cost(0.0)  {
  (void)_alloc;
    }



   typedef uint16_t _x_type;
  _x_type x;

   typedef uint16_t _y_type;
  _y_type y;

   typedef float _cost_type;
  _cost_type cost;




  typedef boost::shared_ptr< ::om17::CellCost_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::om17::CellCost_<ContainerAllocator> const> ConstPtr;

}; // struct CellCost_

typedef ::om17::CellCost_<std::allocator<void> > CellCost;

typedef boost::shared_ptr< ::om17::CellCost > CellCostPtr;
typedef boost::shared_ptr< ::om17::CellCost const> CellCostConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::om17::CellCost_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::om17::CellCost_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace om17

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'om17': ['/home/phobos/om_ws/src/om17/msg', '/home/phobos/om_ws/src/om17/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::om17::CellCost_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::om17::CellCost_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::om17::CellCost_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::om17::CellCost_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::om17::CellCost_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::om17::CellCost_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::om17::CellCost_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e3fe3b7498573a946fcc553657ef0ef";
  }

  static const char* value(const ::om17::CellCost_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e3fe3b7498573a9ULL;
  static const uint64_t static_value2 = 0x46fcc553657ef0efULL;
};

template<class ContainerAllocator>
struct DataType< ::om17::CellCost_<ContainerAllocator> >
{
  static const char* value()
  {
    return "om17/CellCost";
  }

  static const char* value(const ::om17::CellCost_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::om17::CellCost_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 x\n\
uint16 y\n\
float32 cost\n\
";
  }

  static const char* value(const ::om17::CellCost_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::om17::CellCost_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.cost);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CellCost_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::om17::CellCost_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::om17::CellCost_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.y);
    s << indent << "cost: ";
    Printer<float>::stream(s, indent + "  ", v.cost);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OM17_MESSAGE_CELLCOST_H
